<?php
/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
include_once $GLOBALS['THRIFT_ROOT'].'/packages/sqlet_service/sqlet_service_types.php';

$GLOBALS['sqlet_service_CONSTANTS'] = array();

$GLOBALS['sqlet_service_CONSTANTS']['PROP_OUTPUT_TYPE'] = "output_type";

$GLOBALS['sqlet_service_CONSTANTS']['PROP_OUTPUT_TBLNAME'] = "output_tblname";

?>
