/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package gridool.sqlet.api;

public enum CommandType implements org.apache.thrift.TEnum {
    MAP_SHUFFLE(0), MAP_ONLY(1), REDUCE(2);

    private final int value;

    private CommandType(int value) {
        this.value = value;
    }

    /**
     * Get the integer value of this enum value, as defined in the Thrift IDL.
     */
    public int getValue() {
        return value;
    }

    /**
     * Find a the enum type by its integer value, as defined in the Thrift IDL.
     * @return null if the value is not found.
     */
    public static CommandType findByValue(int value) {
        switch(value) {
            case 0:
                return MAP_SHUFFLE;
            case 1:
                return MAP_ONLY;
            case 2:
                return REDUCE;
            default:
                return null;
        }
    }
}
