/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package gridool.sqlet.api;

public enum InputOutputType implements org.apache.thrift.TEnum {
    CSV(0), JSON(1), XML(2);

    private final int value;

    private InputOutputType(int value) {
        this.value = value;
    }

    /**
     * Get the integer value of this enum value, as defined in the Thrift IDL.
     */
    public int getValue() {
        return value;
    }

    /**
     * Find a the enum type by its integer value, as defined in the Thrift IDL.
     * @return null if the value is not found.
     */
    public static InputOutputType findByValue(int value) {
        switch(value) {
            case 0:
                return CSV;
            case 1:
                return JSON;
            case 2:
                return XML;
            default:
                return null;
        }
    }
}
