#
# Autogenerated by Thrift Compiler (0.7.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'sqlet_service_types'

PROP_OUTPUT_TYPE = %q"output_type"

PROP_OUTPUT_TBLNAME = %q"output_tblname"

