#
# Autogenerated by Thrift Compiler (0.7.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

from thrift.Thrift import *
from ttypes import *

PROP_OUTPUT_TYPE = "output_type"
PROP_OUTPUT_TBLNAME = "output_tblname"
